const theme = {
  light: {
    theme: "light",
    color: "black",
    backgroundColor: "#eee",
    cellTextColor: "red",
    black: "white",
    keyBoardLetterColor: "lightgray",
    keyLetterColor: "black",
    darkgrey: "#9595a6",
    primary: "#4a8f52",
    secondary: "#e89736",
    keyBackgroundColor: "yellow",
    title: "black",
    info: "black",
  },
  dark: {
    theme: "dark",
    color: "white",
    backgroundColor: "#10172a",
    black: "#1F2632",
    darkgrey: "#3A3A3D",
    grey: "#818384",
    lightgrey: "#D7DADC",
    primary: "#4a8f52",
    secondary: "#e89736",
    cellText: "#D7DADC",
    keyBoardLetterColor: "#818384",
    keyLetterColor: "#D7DADC",
    keyBackgroundColor: "#D7DADC",
    title: "white",
    info: "white",
  },
};
export default theme;
